version: 0.2
phases:
  pre_build:
    commands:
      - echo Using build artifact name as $BUILD_ARTIFACT_NAME
  build:
    commands:
      - zip -rv $BUILD_ARTIFACT_NAME.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: .
  files:
    - $BUILD_ARTIFACT_NAME.zip